//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptos
    {
        public int ID { get; set; }
        public int ID_Pagos { get; set; }
        public string Proyecto { get; set; }
        public string Cuenta { get; set; }
        public string Subcuenta { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Pagos Pagos { get; set; }
    }
}
