//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string RfcEmpresa { get; set; }
        public string FolioFiscal { get; set; }
        public string Folio { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Proveedor { get; set; }
        public string RfcProveedor { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<bool> CheckRfcProveedor { get; set; }
        public Nullable<bool> CheckCP { get; set; }
        public Nullable<bool> CheckRegFiscal { get; set; }
        public Nullable<bool> CheckRfcCliente { get; set; }
        public Nullable<bool> CheckUnidad { get; set; }
        public Nullable<bool> CheckDescripcion { get; set; }
        public Nullable<bool> CheckIvaDesglosado { get; set; }
        public Nullable<bool> CheckUsoCFDI { get; set; }
        public Nullable<bool> CheckMetodoPago { get; set; }
        public Nullable<bool> CheckFormaPago { get; set; }
        public Nullable<bool> CheckTipoCFDI { get; set; }
        public string EstatusPago { get; set; }
        public string Observaciones { get; set; }
        public string FechaPago { get; set; }
        public Nullable<bool> Block { get; set; }
        public string IvaDesglosado { get; set; }
    }
}
