//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPagosVW
    {
        public int IDs { get; set; }
        public string folio { get; set; }
        public string Beneficiario { get; set; }
        public string Razon { get; set; }
        public string Autorizo { get; set; }
        public string Solicito { get; set; }
        public System.DateTime Fecha_de_Pago { get; set; }
        public System.DateTime Fecha_de_la_Solicitud { get; set; }
        public string Hora_de_Elaboracion { get; set; }
        public string Tipo_da_Pago { get; set; }
        public string Forma_de_Pago { get; set; }
        public string Proyecto { get; set; }
        public string Cuenta { get; set; }
        public string Subcuenta { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.TimeSpan> HoraSolicitud { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public string CategoriaNP { get; set; }
        public string ResponsableNP { get; set; }
        public bool Mov_Interno { get; set; }
    }
}
