//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagos()
        {
            this.Conceptos = new HashSet<Conceptos>();
        }
    
        public int ID { get; set; }
        public int ID_Usuario { get; set; }
        public string Beneficiario { get; set; }
        public string Razon { get; set; }
        public string Autorizo { get; set; }
        public string Solicito { get; set; }
        public System.DateTime FechaDePago { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Programacion { get; set; }
        public string FormaPago { get; set; }
        public string folio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.TimeSpan> HoraSolicitud { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public string CategoriaNP { get; set; }
        public string ResponsableNP { get; set; }
        public bool MovInt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conceptos> Conceptos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
