//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class admAlmacenes
    {
        public int CIDALMACEN { get; set; }
        public string CCODIGOALMACEN { get; set; }
        public string CNOMBREALMACEN { get; set; }
        public System.DateTime CFECHAALTAALMACEN { get; set; }
        public int CIDVALORCLASIFICACION1 { get; set; }
        public int CIDVALORCLASIFICACION2 { get; set; }
        public int CIDVALORCLASIFICACION3 { get; set; }
        public int CIDVALORCLASIFICACION4 { get; set; }
        public int CIDVALORCLASIFICACION5 { get; set; }
        public int CIDVALORCLASIFICACION6 { get; set; }
        public string CSEGCONTALMACEN { get; set; }
        public string CTEXTOEXTRA1 { get; set; }
        public string CTEXTOEXTRA2 { get; set; }
        public string CTEXTOEXTRA3 { get; set; }
        public System.DateTime CFECHAEXTRA { get; set; }
        public double CIMPORTEEXTRA1 { get; set; }
        public double CIMPORTEEXTRA2 { get; set; }
        public double CIMPORTEEXTRA3 { get; set; }
        public double CIMPORTEEXTRA4 { get; set; }
        public int CBANDOMICILIO { get; set; }
        public string CTIMESTAMP { get; set; }
        public string CSCALMAC2 { get; set; }
        public string CSCALMAC3 { get; set; }
        public int CSISTORIG { get; set; }
    }
}
