//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class admCaracteristicasValores
    {
        public int CIDVALORCARACTERISTICA { get; set; }
        public int CIDPADRECARACTERISTICA { get; set; }
        public string CVALORCARACTERISTICA { get; set; }
        public string CNEMOCARACTERISTICA { get; set; }
    }
}
